server:
  port: 8083
  servlet:
    context-path: /xcx
spring:
  application:
    name: tysxcx
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath*:com/tys/**/mapper/*Mapper.xml
mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
wx:
  appId: wxcb8eb30c4ca54bad
  appSecret: d110574dda99ff39878cf55e09b16a24


---
spring:
  profiles: dev
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: jianyuan
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tys?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
es:
  username:
  password:
  cluster-nodes: 192.168.0.217
  port: 9200
  connect_time_out: 3000
  socket_time_out: 30000
  connection_request_time_out: 500
  max_connect_num: 500
  max_connect_per_route: 500
logging:
  level:
    cn.jay.repository: ALL
    io.swagger.models.parameters.AbstractSerializableParameter: error
swagger:
  enable: true


---
spring:
  profiles: home
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    host: 114.55.164.92
    port: 6379
    database: 0
    password: Tiaoyanshi123
  datasource:
    url: jdbc:mysql://rm-bp13qr10r05sfdv65io.mysql.rds.aliyuncs.com:3306/tys?characterEncoding=utf8&useSSL=true
    username: tys
    password: Tiaoyanshi123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
es:
  username: elastic
  password: Tiaoyanshi123
  cluster-nodes: es-cn-v0h14rpvi0002sjne.public.elasticsearch.aliyuncs.com
  port: 9200
  connect_time_out: 3000
  socket_time_out: 30000
  connection_request_time_out: 500
  max_connect_num: 500
  max_connect_per_route: 500
logging:
  level:
    cn.jay.repository: ALL
swagger:
  enable: true


---
spring:
  profiles: prod
  http:
    encoding:
      charset: utf8
  session:
    store-type: redis
  redis:
    host: 192.168.0.15
    port: 6379
    database: 0
    password: Tiaoyanshi123
  datasource:
    url: jdbc:mysql://rm-bp13qr10r05sfdv65.mysql.rds.aliyuncs.com:3306/tys?characterEncoding=utf8&useSSL=true
    username: tys
    password: Tiaoyanshi123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
es:
  username: elastic
  password: Tiaoyanshi123
  cluster-nodes: es-cn-v0h14rpvi0002sjne.elasticsearch.aliyuncs.com
  port: 9200
  connect_time_out: 3000
  socket_time_out: 30000
  connection_request_time_out: 500
  max_connect_num: 500
  max_connect_per_route: 500
logging:
  level:
    cn.jay.repository: INFO

swagger:
  enble: false
