package com.tys.service.imp.provider;

import com.tys.entity.vo.EquipMent;
import org.apache.ibatis.jdbc.SQL;

public class EquipMentSqlProvider {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Wed Mar 06 10:30:13 CST 2019
     */
    public String insertSelective(EquipMent record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("equipment");

        if (record.getEmName() != null) {
            sql.VALUES("em_name ","#{emName,jdbcType=VARCHAR}");
        }

        if (record.getEmAddress() != null) {
            sql.VALUES("em_address", "#{emAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLongitude() != null) {
            sql.VALUES("em_longitude", "#{emLongitude,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLatitude() != null) {
            sql.VALUES("em_latitude", "#{emLatitude,jdbcType=VARCHAR}");
        }
        
        if (record.getEmStatus() != null) {
            sql.VALUES("em_status", "#{emStatus,jdbcType=TINYINT}");
        }

        if (record.getEmHardware() != null) {
            sql.VALUES("em_hardware", "#{emHardware,jdbcType=TINYINT}");
        }

        if(record.getEmProvince() != null){
            sql.VALUES("em_province","#{emProvince,jdbcType=VARCHAR}");
        }

        if(record.getEmCity() != null){
            sql.VALUES("em_city","#{emCity,jdbcType=VARCHAR}");
        }
        
        if (record.getEmInfo() != null) {
            sql.VALUES("em_info", "#{emInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLasttime() != null) {
            sql.VALUES("em_lasttime", "#{emLasttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEmImie() != null) {
            sql.VALUES("em_imie", "#{emImie,jdbcType=VARCHAR}");
        }

        if(record.getEmIccid() !=null){
            sql.VALUES("em_iccid", "#{emIccid,jdbcType=VARCHAR}");
        }

        if(record.getEmNumber() !=null){
            sql.VALUES("em_number", "#{emNumber,jdbcType=VARCHAR}");
        }

        if(record.getEmUpushId() != null){
            sql.VALUES("em_upush_id", "#{emUpushId,jdbcType=VARCHAR}");
        }

        if(record.getEmVersion() != null){
            sql.VALUES("em_version", "#{emVersion,jdbcType=VARCHAR}");
        }

        if (record.getPlaceAddress() != null) {
            sql.VALUES("place_address", "#{placeAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getPlaceInfo() != null) {
            sql.VALUES("place_info", "#{placeInfo,jdbcType=VARCHAR}");
        }

        if(record.getEmPhoto() !=null){
            sql.VALUES("em_photo", "#{emPhoto,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment
     *
     * @mbg.generated Wed Mar 06 10:30:13 CST 2019
     */
    public String updateByPrimaryKeySelective(EquipMent record) {
        SQL sql = new SQL();
        sql.UPDATE("equipment");

        if (record.getEmName() != null) {
            sql.SET("em_name = #{emName,jdbcType=VARCHAR}");
        }

        if (record.getEmAddress() != null) {
            sql.SET("em_address = #{emAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLongitude() != null) {
            sql.SET("em_longitude = #{emLongitude,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLatitude() != null) {
            sql.SET("em_latitude = #{emLatitude,jdbcType=VARCHAR}");
        }

        if(record.getEmProvince() != null){
            sql.SET("em_province = #{emProvince,jdbcType=VARCHAR}");
        }

        if(record.getEmCity() != null){
            sql.SET("em_city = #{emCity,jdbcType=VARCHAR}");
        }
        
        if (record.getEmStatus() != null) {
            sql.SET("em_status = #{emStatus,jdbcType=TINYINT}");
        }
        
        if (record.getEmInfo() != null) {
            sql.SET("em_info = #{emInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getEmLasttime() != null) {
            sql.SET("em_lasttime = #{emLasttime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEmImie() != null) {
            sql.SET("em_imie = #{emImie,jdbcType=VARCHAR}");
        }

        if (record.getEmIccid() != null) {
            sql.SET("em_iccid = #{emIccid,jdbcType=VARCHAR}");
        }

        if(record.getEmNumber() !=null){
            sql.SET("em_number = #{emNumber,jdbcType=VARCHAR}");
        }

        if(record.getEmUpushId() != null){
            sql.SET("em_upush_id = #{emUpushId,jdbcType=VARCHAR}");
        }

        if(record.getEmVersion() != null){
            sql.SET("em_version = #{emVersion,jdbcType=VARCHAR}");
        }
        
        if (record.getPlaceAddress() != null) {
            sql.SET("place_address = #{placeAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getPlaceInfo() != null) {
            sql.SET("place_info = #{placeInfo,jdbcType=VARCHAR}");
        }
        if (record.getEmPhoto() != null){
            sql.SET("em_photo = #{emPhoto,jdbcType=VARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }


    public String queryByEntity(EquipMent record){
       return new SQL(){
           {
               SELECT("em.id id, em_name, em_address, em_longitude, em_latitude,em_province, em_city, em_status, em_hardware, em_info, em_lasttime, em_imie,em_iccid ,em_number, em_upush_id, em_version, place_address, place_info,em_photo,ad.advertise advertise,ad.advertise_type advertise_type");
               FROM("equipment em");
               LEFT_OUTER_JOIN("em_advertise ad on em.id = ad.em_id");
               WHERE("em.status = 1");
               if(record.getEmProvince() != null ){
                   WHERE("em_province = #{emProvince,jdbcType=VARCHAR}");
               }
               if(record.getEmCity() != null){
                   WHERE("em_city = #{emCity,jdbcType=VARCHAR}");
               }
               if(record.getEmName() != null){
                   WHERE("em_name like concat('%',#{emName,jdbcType=VARCHAR},'%')");
               }
               if(record.getEmVersion() != null){
                   WHERE("em_version like concat('%',#{emVersion,jdbcType=VARCHAR},'%')");
               }
               if(record.getEmStatus() !=null){
                   WHERE("em_status = #{emStatus,jdbcType=TINYINT}");
               }
               if(record.getEmHardware() !=null){
                   WHERE("em_hardware = #{emHardware,jdbcType=TINYINT}");
               }
               if(record.getEmLasttimeStart() != null){
                   WHERE("em_lasttime >= #{emLasttimeStart,jdbcType=TIMESTAMP}");
               }
               if(record.getEmLasttimeEnd() != null){
                   WHERE("em_lasttime <= #{emLasttimeEnd,jdbcType=TIMESTAMP}");
               }
           }
       }.toString();
    }

}