package com.tys.service.imp.provider;

import com.tys.entity.vo.TagInfo;
import org.apache.ibatis.jdbc.SQL;

public class TagInfoSqlProvider {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taginfo
     *
     * @mbg.generated Wed Mar 06 10:48:30 CST 2019
     */
    public String insertSelective(TagInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("taginfo");
        
        if (record.getTagType() != null) {
            sql.VALUES("tag_type", "#{tagType,jdbcType=TINYINT}");
        }
        
        if (record.getTagStatus() != null) {
            sql.VALUES("tag_status", "#{tagStatus,jdbcType=TINYINT}");
        }
        
        if (record.getTagContent() != null) {
            sql.VALUES("tag_content", "#{tagContent,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taginfo
     *
     * @mbg.generated Wed Mar 06 10:48:30 CST 2019
     */
    public String updateByPrimaryKeySelective(TagInfo record) {
        SQL sql = new SQL();
        sql.UPDATE("taginfo");
        
        if (record.getTagType() != null) {
            sql.SET("tag_type = #{tagType,jdbcType=TINYINT}");
        }
        
        if (record.getTagStatus() != null) {
            sql.SET("tag_status = #{tagStatus,jdbcType=TINYINT}");
        }
        
        if (record.getTagContent() != null) {
            sql.SET("tag_content = #{tagContent,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    public String querySelective(TagInfo record){
        return new SQL(){
            {
                SELECT("id, tag_type, tag_status, tag_content");
                FROM("taginfo");
                WHERE("status = 1");
                if(record.getTagContent() != null){
                    WHERE("tag_content like concat('%',#{tagContent,jdbcType=VARCHAR},'%')");
                }
                if(record.getTagType() != null){
                    WHERE("tag_type = #{tagType,jdbcType=TINYINT}");
                }
                if(record.getTagStatus() != null){
                    WHERE("tag_status = #{tagStatus,jdbcType=TINYINT}");
                }
            }
        }.toString();
    }

}