server:
  port: 8082
spring:
  application:
    name: tysdemo
  profiles:
    active: dev
wx:
  appId: wxec93ba469a56e5c1
  appSecret: 3fa721cd5b8fa59691d79da7d194a2c5
ossServer:
  endpoint: sts.cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIXHSmc5UnRHKK
  accessKeySecret: PtYYJP6THLNYPzalL7sQNYh49K0r3X
  roleArn: acs:ram::1622753062289994:role/dljy-public-read-role

---
spring:
  profiles: dev
  http:
    encoding:
      charset: utf8
  redis:
    host: 192.168.0.117
    port: 6379
    database: 0
    password: jianyuan
  datasource:
    url: jdbc:mysql://192.168.0.117:3306/tys?characterEncoding=utf8&useSSL=true
    username: tys
    password: jianyuan
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.117:9300
es:
  username:
  password:
  cluster-nodes: 192.168.0.117
  port: 9200
  connect_time_out: 3000
  socket_time_out: 30000
  connection_request_time_out: 500
  max_connect_num: 500
  max_connect_per_route: 500